### PR TITLE
fix: handle addition-only and deletion-only changes

### LINKED ISSUE #126: review: cannot handle addition only suggestions
A review comment must be on a line. To add a line, you will have to group the suggestion with the previous or next line.

### LINKED ISSUE #127: review: cannot handle deletion only suggestions
You cannot suggest an empty line, so we will have to group the suggestion as a 2 line change with either the previous line or next line.

### PR DESCRIPTION
**Pull request by chingor13**
When partitioning valid hunks from invalid hunks, if we detect addition-only or deletion-only changes, modify the hunk to include the previous or next line after the change (assuming it still fits in the valid commentable lines).

Fixes #126 
Fixes #127

### CODE REVIEW

File: test/scope-handler.ts [hunk 1]
```diff
@@ -156,4 +156,158 @@ describe('partitionSuggestedHunksByScope', () => {
...
+      newStart: 14,
+      newEnd: 15,
+      newContent: ['previousLine', 'original'],
+    };
+    expect(validHunks.get('file1.txt')!.length).to.equal(1);
+    expect(validHunks.get('file1.txt')).to.eql([expectedHunk]);
+    expect(invalidHunks.size).to.equal(0);
+  });
+
+  it('allows an addition only suggestion at the beginning of the range', () => {
```
Comment (bcoe) [inline test/scope-handler.ts:198]: These tests are looking really solid, excited to see this moving forward 👍

**Review by bcoe — APPROVED** [review]
