### PR TITLE
fix: prevent cascading tests by having sinon reset all stubs

### LINKED ISSUE #36: Cascading test failures: stubs not restored when tests fail
This code base uses `Sinon` test stubs. On test suite failure, the subsequent code will not be executed, which means any restorative in-line code will not be executed. Several files in the codebase test suite have in-line restorations. Therefore this will cause cascading failures when other tests try to create a stub for the same method.

According to [Best practices using Sinon](https://semaphoreci.com/community/tutorials/best-practices-for-spies-stubs-and-mocks-in-sinon-js) a  feasible solution is to have stub globals and a before-each/after-each to restore the global stub.

Files to change:
- [ ] `test/fork.ts`
- [ ] `test/branch.ts`
- [ ] `test/pr.ts`

Note:
- the other option according to the link is to wrap a function with sinon.test but that did not work/compile

### PR DESCRIPTION
**Pull request by TomKristie**
In order to not call external APIs during unit tests, we make use of `Sinon` stubs. Tests are designed such that each test a new stub is creating, returning specific values. However, when one unit test fails, proceeding tests fail because the previous stub was not restored, and a duplicate stub is being made on a function.

*Solution:* before each test run, reset the sinon environment which resets all stubs.
Also use globals for tests that stub the same method such that they can be called by a `beforeEach` outside of a test and restored.

Fixes #36 
- [x] branching tests
- [x] forking tests

### CODE REVIEW

File: test/branch.ts [hunk 1]
```diff
@@ -40,9 +43,12 @@ describe('Branch module', async () => {
   };
 
   describe('Get branch head', () => {
+    beforeEach(() => {
```
Comment (azizsonawalla) [inline test/branch.ts:46]: If you're adding the same `beforeEach` function to every describe block, you can just put it once in the parent describe block and it will be called before all nested tests

File: test/fork.ts [hunk 2]
```diff
@@ -22,11 +22,16 @@ before(() => {
...
 });
 
+let stub = sinon.stub(octokit.repos, 'createFork');
+
 describe('Fork', async () => {
   const upstream = {owner: 'upstream-owner', repo: 'upstream-repo'};
   const responseData = await import('./fixtures/create-fork-response.json');
 
   describe('Octokit createFork function', () => {
+    beforeEach(() => {
```
Comment (azizsonawalla) [inline test/fork.ts:32]: same here

File: test/branch.ts (hunk 1 above)
Comment (TomKristie) [reply test/branch.ts:43]: It doesn't seem to work on my environment. When I add it just below the root describe, all the tests fail. I think this is because `beforeEach` refers to any `it` blocks in scope. It doesn't go to nested describe blocks.

see [stack overflow](https://stackoverflow.com/a/41855326) for more details.

File: test/branch.ts [hunk 3]
```diff
@@ -48,19 +51,18 @@ describe('Branch module', async () => {
...
         repo: origin.repo,
         branch: 'master',
       });
-
-      // restore
-      getBranchStub.restore();
     });
   });
 
   describe('The create branch function', () => {
```
Comment (bcoe) [inline test/branch.ts:62]: A bit of a nit, but in most cases I'll make the describe call out a specific Function or Class, vs., a phrase like in an `it` statement:

```
describe('FooClas', () => {
  describe('barMethod', () => {
     it("has some behavior I'm testing")
     it("exhibits some other behavior I'm testing")
  })
})
```

File: test/branch.ts [hunk 4]
```diff
@@ -40,6 +40,9 @@ describe('Branch module', async () => {
   };
 
   describe('Get branch head', () => {
+    beforeEach(() => {
+      sinon.restore();
```
Comment (JustinBeckwith) [inline test/branch.ts:44]: So generally, I will do a few things different here.  I create a sandbox so that I don't worry about test interference:
```js
const sandbox = sinon.createSandbox();
```

Then, in an `afterEach`, I tend to do my restore on the sandbox:
```js
afterEach(() => sandbox.restore());
```

When you go to create a stub, use the `sandbox` instead of `sinon` at the root to avoid weird leaks and confusion in async tests:
```js
const stub = sandbox.stub(myClass, 'myMethod').resolves('🥳');
```

**Comment by TomKristie** [comment]
@bcoe @azizsonawalla Ah it is because I don't think mocha likes async describe blocks. I removed it. The before each statement wasn't running at all. My theory is that it might have to do with the fact that I used arrow function callbacks and the `this` binding the before each vanished.

File: test/branch.ts (hunk 4 above)
Comment (TomKristie) [reply test/branch.ts:44]: I found this on [stackoverflow](https://stackoverflow.com/a/55251560)
> Since sinon@5.0.0, the sinon object is a default sandbox.
Is a distinct sandbox preferred?

**Comment by bcoe** [comment]
> I tested my theory is that it might have to do with the fact that I used arrow function callbacks and the this binding the before each vanished. It came back positive.

Were you invoking `this` inside `arrow` functions, mind sharing what the original code looked like that was requiring the multiple `beforeEach` statements?

**Comment by TomKristie** [comment]
@bcoe I did not invoke `this` inside arrow functions.
Here is something I can reproduce repeatedly on my local machine.
```
describe('Outer test', async () => {
  beforeEach(() => {
    console.log('Outer describe');
  });
  await import('./fixtures/create-branch-response.json');
  describe('Inner test', () => {
    beforeEach(() => {
      console.log('Inner describe');
    });
    it('Should pass!', () => {
      expect(true).true
    })
  })
})
```
Will output:
```

  Inner test
Inner describe
    ✓ Should pass!
```
