### PR TITLE
fix(cli,action): when process fails, make exit code 1

### LINKED ISSUE #72: Incorrect exit code on failure
Not sure if this is from the CLI or the GitHub action, but a rejected promise is not causing the build step to fail.

Example: https://github.com/chingor13/actions-test/runs/968409994?check_suite_focus=true - the "Open Pull Request" step should have failed.

### PR DESCRIPTION
**Pull request by TomKristie**
**Assumptions**: To my knowledge, in order to get a step to fail, the process exit code has to be 1: https://docs.github.com/en/actions/creating-actions/setting-exit-codes-for-actions

**Scenario:**

Currently when the node process fails, it always exits with code 0.

Tested by running local script:
```
if code-suggester pr \
--upstream-repo="dne" \
--upstream-owner="TomKristie" \
--description="describe" \
--title="title" \
--branch="something" \
--primary="master" \
--message="some message" \
--git-dir="./kubernetes"; then
    exit 0
else
    echo "failure exit code non-zero"
    exit 1
fi
```

which tries to fork a non-existent repo.

The output is
```
{"level":30,"time":1597342089072,"pid":8411,"hostname":"penguin","msg":"Starting GitHub PR workflow..."}
{"level":50,"time":1597342089474,"pid":8411,"hostname":"penguin","msg":"Error when forking"}
{"level":50,"time":1597342089474,"pid":8411,"hostname":"penguin","msg":"Workflow failed"}
{"level":50,"time":1597342089474,"pid":8411,"hostname":"penguin","stack":"Error: HttpError: Not Found\n    at Object.fork (/home/kristietom/code-suggester/build/src/github-handler/fork-handler.js:44:15)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async Object.createPullRequest (/home/kristietom/code-suggester/build/src/index.js:59:20)\n    at async Object.main (/home/kristietom/code-suggester/build/src/bin/workflow.js:42:17)","type":"Error","msg":"HttpError: Not Found"}
failure exit code non-zero
```
Fixes #72 🦕

### CODE REVIEW

File: entrypoint.sh [hunk 1]
```diff
@@ -24,4 +24,8 @@ code-suggester $INPUT_COMMAND \
 --message="$INPUT_MESSAGE" \
 --force="$INPUT_FORCE" \
 --maintainers-can-modify="$INPUT_MAINTAINERS_CAN_MODIFY" \
---git-dir="$INPUT_GIT_DIR"
\ No newline at end of file
+--git-dir="$INPUT_GIT_DIR"; then
+    exit 0
+else
+    exit 1
```
Comment (chingor13) [inline entrypoint.sh:30]: You could do "set -e" at the top of the bash script instead. It tells bash to fail if any command in the script fails.

Comment (TomKristie) [reply entrypoint.sh:30]: for script: `exit_code.sh`

```
set -e

code-suggester pr \
--upstream-repo="dne" \
--upstream-owner="TomKristie" \
--description="describe" \
--title="title" \
--branch="something" \
--primary="master" \
--message="some message" \
--git-dir="./kubernetes"
```
after running `./exit_code.sh`
and then `echo $?` it outputs exit code 0. According to the docs it looks like it needs to have an error code of 1 in order for the step to fail.

Does `set -e` make the script fail with error 1?
